### ISSUE TITLE
 F5 Distributed Cloud - WAF/WAAP Deeper Dive: some attacks don't work as expected

### ISSUE THREAD

**Issue by jamesaffeld** [f5devcentral/f5-agility-labs-xc#139]
Lab 1 Task 3 Step 2 has the user launch 4 attacks. 

    /?cmd=cat%20/etc/passwd
    /product?id=4%20OR%201=1
    /../../../../etc/shadow
    /cart?search=aaa’><script>prompt(‘Please+enter+your+password’);</script>

The request hangs. 

The second sees a connection reset.

**Comment by lesleycw** [comment]
Tests will be addressed in Lab rewrite.
