### ISSUE TITLE
class 2 - Lab 1 Deploying and Managing F5 Distributed Cloud Web Application Firewall Configuration - only 1 of 3 attacks blocked as expected

### ISSUE THREAD

**Issue by jamesaffeld** [f5devcentral/f5-agility-labs-xc#206]
After configuring the WAF, I made the 3 requests to test. The first timed out, the second had a connection reset, and only the third showed the expected rejection page with id. 

I do not have the permissions to investigate the properties of shared/base-appfw to troubleshoot. 

See attached gif. 
![XC-WAF-Lab1-results2](https://github.com/f5devcentral/f5-agility-labs-xc/assets/55117700/1eeba69f-03b8-4721-a495-1d11ac5f0650)

**Comment by jamesaffeld** [comment]
This is for Task 3: Testing the WAF Policy & Reviewing Event Data

**Comment by jamesaffeld** [comment]
One notion - have the user create the firewall object to be used, rather than employing shared/base-appfw. 

This sets up a "See one, do one, fix one" sequence of labs. Right now we "do one we can't see and can't fix"

**Comment by lesleycw** [comment]
Task2 has you build an app-fw policy.  Please follow Task2 completely (including steps 3-8) to build it correctly
