### ISSUE TITLE
class 2 lab 2 Reviewing Signature-based Bot Strategies - asks us to edit object we haven't created

### ISSUE THREAD

**Issue by jamesaffeld** [f5devcentral/f5-agility-labs-xc#207]
Task 1: Reviewing Signature-based Bot protection
2. on your App Firewall policy **THAT DOESN'T EXIST** \<namespace\>-appfw, click the three dots...

I just used the shared/base-appfw. I couldn't edit it, couldn't clone it. 

I created a new object \<namespace\>-appfw with the signature-based bot protection and left all the defaults except for enabling enforcement. Signature-based bot protection was configured as specified in the lab guide.

**Comment by lesleycw** [comment]
Please complete the exercise by completing steps 3-8 of task 2 in the lab guide
