### ISSUE TITLE
Class 2 Lab 3 - Malicious Users NEEDS TEST to demontrate feature. 

### ISSUE THREAD

**Issue by jamesaffeld** [f5devcentral/f5-agility-labs-xc#208]
There is no malicious user testing in the lab to show the feature works. 

Just walking through the config is not enough.

**Comment by lesleycw** [comment]
Unfortunately lab timing and current lab construction does not allow sufficient window of opportunity for full evaluation.   Future lab updates will include more pre-staged/automated workloads to show outcomes rather than just wlk-throughs
