### ISSUE TITLE
Class 1 Lab 4 Introduction to F5 Distributed Cloud DNS - permissions issue prevent Zone creation - Task 2

### ISSUE THREAD

**Issue by jamesaffeld** [f5devcentral/f5-agility-labs-xc#212]
Can't complete Task 2 or the rest of the lab. 
![XC-DNS-Zone-creation-permissions-fail](https://github.com/f5devcentral/f5-agility-labs-xc/assets/55117700/964ea822-0518-4397-be02-3ef6be384df2)

**Comment by lesleycw** [comment]
This lab is a guided walk-through as presented in the lab "Instructor Lead".  We will add additional notes to make this clear

**Comment by lesleycw** [comment]
Closing.
