### ISSUE TITLE
HTTP Load Balancer - "Advanced Configuration" is now "Other Settings"

### ISSUE THREAD

**Issue by bradotlin** [f5devcentral/f5-agility-labs-xc#60]
In Lab 3 https://github.com/f5devcentral/f5-agility-labs-xc/blob/dev/docs/class1/lab3.rst 

https://github.com/f5devcentral/f5-agility-labs-xc/blob/dev/docs/class1/lab3.rst#exercise-3-configure-local-vip
Task 3 Exercise 3: Configure Local VIP; the instructions say to go under "Advanced Configuration". This now appears to be called "Other Settings".

"Where to Advertise the VIP" is now called "VIP Advertisement"
The "Advertise Custom" option is now called "Custom"
Step 3, Next to "Custom Advertise VIP Configuration" click on "Show Advanced Fields" does not appear to be necessary as there is no "Show Advanced Fields" button to click.

https://github.com/f5devcentral/f5-agility-labs-xc/blob/dev/docs/class1/lab3.rst#exercise-4-configure-waf-policy
Exercise 4: Configure WAF Policy
The Security Configuration section in the console is before the "Other Settings" section, so maybe the WAF section shoul dcome first in the guide?

**Comment by lesleycw** [comment]
Lab updated
